services:
  web:
    build:
      context: .
      target: runtime
      args:
        # $UID must be exported for this to work as it's not an environment variable but a shell variable
        - UID
    user: docker_user
    volumes:
      - .:/code:delegated
    ports:
      - '80:80'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.32
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: jouwweb
      MYSQL_DATABASE: dev
      MYSQL_USER: jouwweb
      MYSQL_PASSWORD: jouwweb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: "/usr/bin/mysql --user=jouwweb --password=jouwweb --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    platform: linux/amd64
    ports:
      - '8000:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=jouwweb
      - PMA_PASSWORD=jouwweb
    depends_on:
      - mysql
    volumes:
      - /sessions

volumes:
  mysql-data: