apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Application Secrets
  APP_SECRET: "change_me_to_a_random_string"
  DATABASE_URL: "mysql://jouwweb:jouwweb@mysql-service:3306/dev?serverVersion=8.0.32"
  
  # MySQL Root Password (for the database container)
  MYSQL_ROOT_PASSWORD: "change_me_root"
  MYSQL_PASSWORD: "jouwweb"
  MYSQL_DATABASE: "dev"
  MYSQL_USER: "jouwweb"

  # DigitalOcean Spaces (S3)
  DO_SPACES_REGION: "ams3"
  DO_SPACES_ENDPOINT: "https://ams3.digitaloceanspaces.com"
  DO_SPACES_KEY: "DO00XDTZH8J9DQL3249Y"
  DO_SPACES_SECRET: "PuyLzHwavnH7sav9DbHlODbzZ9igAsTA/c2WBDWvFgY"
  DO_SPACES_BUCKET: "muzieklijstjes-assets"
  ALBUM_COVER_BASE_URL: "https://muzieklijstjes-assets.ams3.digitaloceanspaces.com/"




