apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: register-vibe-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - new.muzieklijstjes.nl
    secretName: register-vibe-tls
  rules:
  - host: new.muzieklijstjes.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: register-vibe-service
            port:
              number: 80


